export const TestInfo = {
  FWID: 7405572,
  RealFWID: 0,
  FWVersion: 58626,
  Mode: 0,
  SensorID: 16,
  SensorInfo: {
    Name: '',
    DPIType: 1,
    DPIs: [
      { Level: 1, DPI: 800, Value: 16 },
      { Level: 2, DPI: 1200, Value: 24 },
      { Level: 3, DPI: 1600, Value: 32 },
      { Level: 4, DPI: 2400, Value: 48 },
      { Level: 5, DPI: 3200, Value: 64 },
    ],
  },
  DPILevels: [2, 2, 2, 2],
  USBReports: [3, 3, 3, 3],
  WLReports: [3, 3, 3, 3],
  LEDEffect: {
    BLMode: 4,
    BLDirection: 0,
    Brightness: 3,
    Speed: 1,
    Color: 7,
    Gain: 0,
    Smooth: 0,
  },
  AdvanceSetting: {
    WLPrimarySleep: 2,
    WLDeepSleep: 1,
    BLEPrimarySleep: 2,
    BLEDeepSleep: 1,
    SilentAltitude: 1,
    UltraLowDelay: false,
    UltraLowPower: false,
    RippleControl: false,
    MoveWakeUp: false,
  },
  Mouse: {
    DeviceID: 1647907365,
    FWID: 0,
    RealFWID: 0,
    FWVersion: 0,
    Online: false,
    Charge: false,
    Battery: 0,
  },
  KB: {
    DeviceID: 0,
    FWID: 0,
    RealFWID: 0,
    FWVersion: 0,
    Online: false,
    Charge: false,
    Battery: 0,
  },
};
